### ISSUE TITLE
Text Decoration

### ISSUE THREAD

**Issue by christoph3r3w** [lemuelmgsn/we-love-web-notes#1]
https://github.com/lemuelmgsn/we-love-web-notes/blob/11f2b298ffe154c0cc02b90394c938d61e545600/index.html#L31-L49

https://lemuelmgsn.github.io/we-love-web-notes/

First, add all your text in HTML then you can decide how to decorate it: as in adding text lines

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/we-love-web-notes/blob/459619f4a7b8565c77f71bf2e270d4bedc475672/index.html#L30-L56

Ik heb bij de eerste 3 notes de html tekst toegevoegd met de design die ik had! Ik heb daarnaast de lijntjes een beetje aangepast zodat de titels op een lijn stonden.

![image](https://github.com/lemuelmgsn/we-love-web-notes/assets/144004180/d7792642-2e46-49a9-8b1a-bcbe5fe766cc)
